### ISSUE TITLE
using LDAPS instead of LDAP

### ISSUE THREAD

**Issue by ganeshramcg** [django-auth-ldap/django-auth-ldap#198]
i am trying to replace LDAP with LDAPS but i am not sure which part i am missing. Below is my code for LDAPS.
The code is not working with LDAPS but it is working fine with LDAP.

import ldap
from django_auth_ldap.config import LDAPSearch, NestedActiveDirectoryGroupType
AUTH_LDAPS_SERVER_URI = "ldaps://example1.com:636" 
AUTH_LDAP_BIND_DN = "CN=SVC_fwauto_prod,OU=Service Accounts,OU=ADCCreated,DC=example1,DC=com"

AUTH_LDAP_USER_SEARCH = LDAPSearch("DC=example1,DC=com",                                                                  
    ldap.SCOPE_SUBTREE, "(sAMAccountName=%(user)s)")
	# Cache settings                                                                                                          
AUTH_LDAP_CACHE_GROUPS = True                                                                                             
AUTH_LDAP_GROUP_CACHE_TIMEOUT = 300                                                                                       

AUTH_LDAP_USER_ATTR_MAP = {                                                                                               
    "first_name": "givenName",                                                                                            
    "last_name": "sn",                                                                                                    
    "email": "mail"                                                                                                       
}                                                                                                                         

AUTHENTICATION_BACKENDS = (                                                                                               
    'django_auth_ldap.backend.LDAPBackend',                                                                               
    'django.contrib.auth.backends.ModelBackend')

**Comment by th3cr0w** [comment]
possibly TLS verification issue like it was in my case
try like this (less secure):

AUTH_LDAP_CONNECTION_OPTIONS = {
    ldap.OPT_X_TLS_REQUIRE_CERT: ldap.OPT_X_TLS_ALLOW
}

**Comment by Sispheor** [comment]
Same here.
I tried with ldaps or ldap with TLS enabled.
I get an error: `SERVER_DOWN({'result': -1, 'desc': "Can't contact LDAP server", 'ctrls': [], 'info': '(unknown error code)'})`

Seems to be related to the certificate verification.
If I test manual from my CLI with `ldapsearch` it's ok so I'm sure i can reach the remote server.

I get 
```yaml
# LDAP auth backend
AUTH_LDAP_SERVER_URI = "ldaps://ed.domain.net:636"
AUTH_LDAP_BIND_DN = "dn=ocpkgweb,ou=Applications,o=domain.com"
AUTH_LDAP_BIND_PASSWORD = "password"
# AUTH_LDAP_USER_SEARCH = LDAPSearch(
#     "ou=people,o=hp.com", ldap.SCOPE_SUBTREE, "(uid=%(user)s)"
# )
AUTH_LDAP_USER_DN_TEMPLATE = "uid=%(user)s,ou=people,o=domain.com"
AUTH_LDAP_START_TLS: False
AUTH_LDAP_GLOBAL_OPTIONS: {
    ldap.OPT_X_TLS_REQUIRE_CERT: ldap.OPT_X_TLS_NEVER
}
```
